// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnEHGMUd6tLun-OMylPztY-fLrwl40zg8',
    appId: '1:761612211519:android:9724bcb51011a96385af8a',
    messagingSenderId: '761612211519',
    projectId: 'prophetic-lifestyle',
    storageBucket: 'prophetic-lifestyle.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6SQvmI8Kn9BfWuZcHS0kdz1PogFFUpTo',
    appId: '1:761612211519:ios:7af19ec7dd95784f85af8a',
    messagingSenderId: '761612211519',
    projectId: 'prophetic-lifestyle',
    storageBucket: 'prophetic-lifestyle.firebasestorage.app',
    androidClientId: '761612211519-sbsof7grin859sba4tc9p1lcv6fvtc2f.apps.googleusercontent.com',
    iosClientId: '761612211519-v32np3ukjqkhnb00vjpp8d3pu1smriic.apps.googleusercontent.com',
    iosBundleId: 'com.prophetic.islam.admin',
  );
}
